### ISSUE TITLE
Include links to pure jstar?

### ISSUE THREAD

**Issue by jalanmiddleton** [SoftwareEngineeringToolDemos/FSE-2011-jstar-eclipse#7]
You had part of this before (and if you think it was better before, feel free to revert it), but links to the pure jstar executable (in the bin folder) and source code (is [this](https://github.com/seplogic/jstar) it?) might be good additions to the links section. For this project, I thought links to the jstar-eclipse plugins were more appropriate for the bare minimum.

**Comment by sumeet29** [comment]
I think it's fine to leave it the way it is.
