### ISSUE TITLE
Experimenting with examples in the paper

### ISSUE THREAD

**Issue by jalanmiddleton** [SoftwareEngineeringToolDemos/FSE-2011-jstar-eclipse#9]
When using the VM, the provided example works perfectly, and the README tells you how to do it, so that's all good, but it's unclear how one might go about implementing some of the examples in the paper.

I tried implementing the binary tree example from the paper. It's clear that the accepted syntax for the actual plug-in differs from what's in the paper, and that can't be helped. 

I looked around for more documentation to explain how it really works, found [this video](https://www.youtube.com/watch?v=Sapg5Kfwqe0) that got it most of the way. It would be a great example to add or reference if you get it working all the way.

**Comment by sumeet29** [comment]
Added the example of binary search tree.

**Comment by sumeet29** [comment]
Due to changes in syntax, it won't be possible to add this example in the VM. However, the example I provided is from the tutorial on the original GitHub repository, and it is easier to understand the working of the tool with the example I included.
